// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type BdbBeer struct {
	BeerID      int64        `json:"beer_id"`
	BreweryID   int64        `json:"brewery_id"`
	TypeID      int64        `json:"type_id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Abv         float64      `json:"abv"`
	Ibu         int32        `json:"ibu"`
}

type BdbBrewery struct {
	BreweryID int64          `json:"brewery_id"`
	CreatedAt time.Time      `json:"created_at"`
	Name      string         `json:"name"`
	Url       sql.NullString `json:"url"`
	Location  sql.NullString `json:"location"`
}

type BdbType struct {
	TypeID    int64     `json:"type_id"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
}

type BdbUser struct {
	UserID       int64        `json:"user_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Active       bool         `json:"active"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Username     string       `json:"username"`
	Hash         string       `json:"hash"`
	Email        string       `json:"email"`
	Token        string       `json:"token"`
	TokenExpires time.Time    `json:"token_expires"`
}
