// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type BdbBeer struct {
	BeerID      int32        `json:"beer_id"`
	BreweryID   int32        `json:"brewery_id"`
	TypeID      int32        `json:"type_id"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Abv         float64      `json:"abv"`
	Ibu         int32        `json:"ibu"`
}

type BdbBrewery struct {
	BreweryID   int32          `json:"brewery_id"`
	CreatedAt   time.Time      `json:"created_at"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Address     sql.NullString `json:"address"`
	City        sql.NullString `json:"city"`
	State       sql.NullString `json:"state"`
	CountryID   int32          `json:"country_id"`
	Phone       sql.NullString `json:"phone"`
	Url         sql.NullString `json:"url"`
}

type BdbCountry struct {
	ID    int32  `json:"id"`
	Value string `json:"value"`
}

type BdbType struct {
	TypeID      int32          `json:"type_id"`
	CreatedAt   time.Time      `json:"created_at"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type BdbUser struct {
	UserID       int32        `json:"user_id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Active       bool         `json:"active"`
	FirstName    string       `json:"first_name"`
	LastName     string       `json:"last_name"`
	Username     string       `json:"username"`
	Hash         string       `json:"hash"`
	Email        string       `json:"email"`
	Token        string       `json:"token"`
	TokenExpires time.Time    `json:"token_expires"`
}
